### ISSUE TITLE
Getting a "Invalid request signature." response on addSignature();

### ISSUE THREAD

**Issue by mrflix** [vbuck/change-js-api#1]
Hello!

I'm getting a "Invalid request signature." response when trying to add a signature to a petition. Because of CORS I'm using the php proxy with my secret key on my server. I've got the api key and the authorization code. I also got the sha256.js library linked.

Any pointers on what could solve this?

–Felix

**Comment by vbuck** [comment]
Hi Felix,

It looks like something is off in the library. I ran a test following your settings, and the auth key is getting stripped of the request (when in proxy mode with a server-side secret key). I'll get a fix rolled out tonight if possible. Thanks for bringing it to my attention.

**Comment by mrflix** [comment]
Thank you for looking into it!

**Comment by vbuck** [comment]
Hey Felix, pull down the latest for commit a39093b. Let me know if that resolves your issue so that I can close this ticket.

**Comment by mrflix** [comment]
Hey Rick. Thanks for the quick response! 
Unfortunately I still get the same error: `"Invalid request signature."`
Any idea what else I can check?

**Comment by vbuck** [comment]
Hey Felix -- Alright, I'll dig deeper. My dev server is down and I'm waiting on a part, so I'll get to it later this week if possible.

**Comment by mrflix** [comment]
**Update**

After a long back and forth I eventually found the error: I can't use it locally. Either its an API limitation or my cURL doesn't work. Using your API from the server (including the proxy) works like a charm! Thank you!

**Comment by vbuck** [comment]
I must have missed this comment. I'm glad it worked out, because I was getting a little puzzled by the issue this morning when looking at the code. You're welcome. Closing the ticket.
